import { createClient } from "@libsql/client";

const dbUrl = process.env.TURSO_DATABASE_URL;
const dbToken = process.env.TURSO_AUTH_TOKEN;

if (!dbUrl) {
  console.error("TURSO_DATABASE_URL not set");
  process.exit(1);
}

const db = createClient({
  url: dbUrl,
  authToken: dbToken,
});

// Real Singapore condo launch data (2024-2026)
const seedCondos = [
  {
    name: "Aurelle of Tampines",
    developer: "Sim Lian Group",
    address: "Tampines Street 62",
    district: 18,
    latitude: 1.3541,
    longitude: 103.9449,
    tenure: "99-year",
    total_units: 760,
    expected_top: "2029",
    launch_date: "2024-10-12",
    status: "launched",
    min_price: 1188000,
    max_price: 2388000,
    min_psf: 1450,
    max_psf: 1650,
    min_sqft: 538,
    max_sqft: 1464,
    bedrooms: JSON.stringify([2, 3, 4, 5]),
    amenities: JSON.stringify([
      "Swimming Pool",
      "Gym",
      "Tennis Court",
      "BBQ Pits",
      "Playground",
      "Clubhouse",
    ]),
    description:
      "Aurelle of Tampines is a highly anticipated EC development located in the heart of Tampines. With excellent connectivity to Tampines MRT and nearby amenities, this development offers modern living at an affordable price point.",
    website_url: "https://aurelleoftampines.com.sg",
  },
  {
    name: "The Orie",
    developer: "City Developments Limited (CDL) & Frasers Property",
    address: "Toa Payoh Lorong 1",
    district: 12,
    latitude: 1.3325,
    longitude: 103.8452,
    tenure: "99-year",
    total_units: 777,
    expected_top: "2029",
    launch_date: "2025-02-22",
    status: "launched",
    min_price: 1098000,
    max_price: 3500000,
    min_psf: 2200,
    max_psf: 2600,
    min_sqft: 452,
    max_sqft: 1496,
    bedrooms: JSON.stringify([1, 2, 3, 4, 5]),
    amenities: JSON.stringify([
      "Sky Garden",
      "Infinity Pool",
      "Gym",
      "Co-working Space",
      "BBQ Pavilion",
      "Jogging Track",
    ]),
    description:
      "The Orie is a premium condominium development in the established Toa Payoh estate. Located near Braddell MRT, it offers excellent connectivity and proximity to schools and amenities.",
    website_url: "https://theorie.com.sg",
  },
  {
    name: "Lentor Central Residences",
    developer: "Hong Leong Holdings & GuocoLand",
    address: "Lentor Central",
    district: 26,
    latitude: 1.4184,
    longitude: 103.8363,
    tenure: "99-year",
    total_units: 478,
    expected_top: "2028",
    launch_date: "2024-07-06",
    status: "launched",
    min_price: 1188000,
    max_price: 2988000,
    min_psf: 2150,
    max_psf: 2400,
    min_sqft: 527,
    max_sqft: 1432,
    bedrooms: JSON.stringify([1, 2, 3, 4]),
    amenities: JSON.stringify([
      "Swimming Pool",
      "Gym",
      "Tennis Court",
      "Function Room",
      "BBQ Area",
    ]),
    description:
      "Lentor Central Residences is part of the exciting Lentor Hills transformation. Connected to Lentor MRT, it offers nature-inspired living with easy access to parks and greenery.",
    website_url: null,
  },
  {
    name: "Parktown Residence",
    developer: "CapitaLand & UOL Group",
    address: "Tampines Ave 11",
    district: 18,
    latitude: 1.3523,
    longitude: 103.9561,
    tenure: "99-year",
    total_units: 1193,
    expected_top: "2030",
    launch_date: "2025-01-18",
    status: "launched",
    min_price: 1100000,
    max_price: 2800000,
    min_psf: 1950,
    max_psf: 2250,
    min_sqft: 527,
    max_sqft: 1389,
    bedrooms: JSON.stringify([2, 3, 4, 5]),
    amenities: JSON.stringify([
      "50m Lap Pool",
      "Sky Terrace",
      "Gym",
      "Tennis Court",
      "Children's Playground",
      "BBQ Pits",
    ]),
    description:
      "Parktown Residence is an integrated development connected to a hawker centre, childcare, and retail mall. Located near Tampines North MRT on the Cross Island Line.",
    website_url: "https://parktownresidence.com.sg",
  },
  {
    name: "Chuan Park",
    developer: "Kingsford & MCC Singapore",
    address: "Lorong Chuan",
    district: 19,
    latitude: 1.3528,
    longitude: 103.8656,
    tenure: "99-year",
    total_units: 916,
    expected_top: "2028",
    launch_date: "2024-07-27",
    status: "launched",
    min_price: 1158000,
    max_price: 3800000,
    min_psf: 2050,
    max_psf: 2350,
    min_sqft: 527,
    max_sqft: 1711,
    bedrooms: JSON.stringify([1, 2, 3, 4, 5]),
    amenities: JSON.stringify([
      "Olympic Pool",
      "Sky Lounge",
      "Gym",
      "Tennis Courts",
      "Putting Green",
    ]),
    description:
      "Chuan Park is a collective sale redevelopment located just 200m from Lorong Chuan MRT. The development offers excellent connectivity and is near reputable schools.",
    website_url: "https://chuanpark.com.sg",
  },
  {
    name: "Norwood Grand",
    developer: "City Developments Limited (CDL)",
    address: "Woodlands Ave 1",
    district: 25,
    latitude: 1.4352,
    longitude: 103.7862,
    tenure: "99-year",
    total_units: 348,
    expected_top: "2029",
    launch_date: "2024-08-17",
    status: "launched",
    min_price: 968000,
    max_price: 2188000,
    min_psf: 1850,
    max_psf: 2100,
    min_sqft: 463,
    max_sqft: 1206,
    bedrooms: JSON.stringify([1, 2, 3, 4]),
    amenities: JSON.stringify([
      "Swimming Pool",
      "Gym",
      "BBQ Pavilion",
      "Playground",
      "Function Room",
    ]),
    description:
      "Norwood Grand is a boutique development in Woodlands, offering affordable luxury living near Woodlands South MRT. Part of the Woodlands Regional Centre transformation.",
    website_url: "https://norwoodgrand.com.sg",
  },
  {
    name: "Meyer Blue",
    developer: "UOL Group & Singapore Land Group",
    address: "Meyer Road",
    district: 15,
    latitude: 1.3062,
    longitude: 103.9044,
    tenure: "Freehold",
    total_units: 226,
    expected_top: "2028",
    launch_date: "2024-04-13",
    status: "launched",
    min_price: 2180000,
    max_price: 12800000,
    min_psf: 2850,
    max_psf: 3300,
    min_sqft: 614,
    max_sqft: 3800,
    bedrooms: JSON.stringify([2, 3, 4, 5]),
    amenities: JSON.stringify([
      "Infinity Pool",
      "Gym",
      "Tennis Court",
      "Sky Lounge",
      "Private Lift",
    ]),
    description:
      "Meyer Blue is an exclusive freehold development in the prestigious East Coast district. Offering sea views and luxury living, it's minutes from Katong and Marine Parade.",
    website_url: "https://meyerblue.com.sg",
  },
  {
    name: "Bagnall Haus",
    developer: "Roxy-Pacific Holdings",
    address: "Upper East Coast Road",
    district: 16,
    latitude: 1.3201,
    longitude: 103.9234,
    tenure: "Freehold",
    total_units: 113,
    expected_top: "2027",
    launch_date: "2024-06-29",
    status: "launched",
    min_price: 1498000,
    max_price: 4500000,
    min_psf: 2400,
    max_psf: 2700,
    min_sqft: 495,
    max_sqft: 1733,
    bedrooms: JSON.stringify([1, 2, 3, 4, 5]),
    amenities: JSON.stringify([
      "Lap Pool",
      "Gym",
      "BBQ Pavilion",
      "Garden",
      "Playground",
    ]),
    description:
      "Bagnall Haus is a boutique freehold development in the Bedok/Upper East Coast area. Near Sungei Bedok MRT on the Thomson-East Coast Line.",
    website_url: "https://bagnallhaus.com.sg",
  },
  {
    name: "Nava Grove",
    developer: "MCL Land",
    address: "Seletar Road",
    district: 28,
    latitude: 1.3941,
    longitude: 103.8678,
    tenure: "99-year",
    total_units: 522,
    expected_top: "2028",
    launch_date: "2024-11-09",
    status: "launched",
    min_price: 1280000,
    max_price: 3200000,
    min_psf: 2050,
    max_psf: 2300,
    min_sqft: 517,
    max_sqft: 1528,
    bedrooms: JSON.stringify([1, 2, 3, 4, 5]),
    amenities: JSON.stringify([
      "Forest Pool",
      "Gym",
      "Tennis Court",
      "Nature Trail",
      "Sky Garden",
    ]),
    description:
      "Nava Grove offers tranquil living amid greenery in Seletar. Connected to nature reserves and parks, it's ideal for families seeking a peaceful environment.",
    website_url: "https://navagrove.com.sg",
  },
  {
    name: "Emerald of Katong",
    developer: "Sim Lian Group",
    address: "Tanjong Katong Road",
    district: 15,
    latitude: 1.3085,
    longitude: 103.8995,
    tenure: "Freehold",
    total_units: 846,
    expected_top: "2028",
    launch_date: "2023-12-09",
    status: "sold_out",
    min_price: 1388000,
    max_price: 4800000,
    min_psf: 2500,
    max_psf: 2850,
    min_sqft: 463,
    max_sqft: 1830,
    bedrooms: JSON.stringify([1, 2, 3, 4, 5]),
    amenities: JSON.stringify([
      "Sky Pool",
      "Gym",
      "Tennis Court",
      "Function Rooms",
      "BBQ Pits",
      "Playground",
    ]),
    description:
      "Emerald of Katong is a mega development in the vibrant Katong/Joo Chiat neighborhood. The freehold status and prime location made it highly sought after.",
    website_url: null,
  },
];

async function seed() {
  console.log("Creating schema...");
  
  await db.execute(`
    CREATE TABLE IF NOT EXISTS condos (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      name TEXT NOT NULL,
      developer TEXT,
      address TEXT,
      district INTEGER,
      latitude REAL,
      longitude REAL,
      tenure TEXT,
      total_units INTEGER,
      expected_top TEXT,
      launch_date TEXT,
      status TEXT DEFAULT 'upcoming',
      min_price INTEGER,
      max_price INTEGER,
      min_psf INTEGER,
      max_psf INTEGER,
      min_sqft INTEGER,
      max_sqft INTEGER,
      bedrooms TEXT,
      amenities TEXT,
      description TEXT,
      website_url TEXT,
      image_url TEXT,
      created_at TEXT DEFAULT CURRENT_TIMESTAMP,
      updated_at TEXT DEFAULT CURRENT_TIMESTAMP
    )
  `);

  console.log("Seeding condos...");

  for (const condo of seedCondos) {
    await db.execute({
      sql: `
        INSERT INTO condos (
          name, developer, address, district, latitude, longitude,
          tenure, total_units, expected_top, launch_date, status,
          min_price, max_price, min_psf, max_psf, min_sqft, max_sqft,
          bedrooms, amenities, description, website_url
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
      `,
      args: [
        condo.name,
        condo.developer,
        condo.address,
        condo.district,
        condo.latitude,
        condo.longitude,
        condo.tenure,
        condo.total_units,
        condo.expected_top,
        condo.launch_date,
        condo.status,
        condo.min_price,
        condo.max_price,
        condo.min_psf,
        condo.max_psf,
        condo.min_sqft,
        condo.max_sqft,
        condo.bedrooms,
        condo.amenities,
        condo.description,
        condo.website_url,
      ],
    });
    console.log(`  ✓ ${condo.name}`);
  }

  console.log(`\nSeeded ${seedCondos.length} condos successfully!`);
}

seed().catch(console.error);
