import { createClient } from "@libsql/client";

const dbUrl = process.env.TURSO_DATABASE_URL;
const dbToken = process.env.TURSO_AUTH_TOKEN;

if (!dbUrl) {
  console.error("TURSO_DATABASE_URL not set");
  process.exit(1);
}

const db = createClient({
  url: dbUrl,
  authToken: dbToken,
});

// Popular resale condos in Singapore (completed developments)
const resaleCondos = [
  {
    name: "The Sail @ Marina Bay",
    developer: "City Developments Limited",
    address: "2 Marina Boulevard",
    district: 1,
    latitude: 1.2789,
    longitude: 103.8536,
    tenure: "99-year",
    total_units: 1111,
    expected_top: "2008",
    status: "completed",
    min_price: 1800000,
    max_price: 15000000,
    min_psf: 2200,
    max_psf: 3500,
    min_sqft: 614,
    max_sqft: 6500,
    bedrooms: JSON.stringify([1, 2, 3, 4, 5]),
    amenities: JSON.stringify(["Sky Pool", "Gym", "Tennis Court", "Concierge", "Sky Lounge"]),
    description: "Iconic waterfront living at Marina Bay. Two towers offering panoramic views of the bay and city skyline.",
  },
  {
    name: "d'Leedon",
    developer: "CapitaLand",
    address: "7 Leedon Heights",
    district: 10,
    latitude: 1.3148,
    longitude: 103.8088,
    tenure: "Freehold",
    total_units: 1715,
    expected_top: "2014",
    status: "completed",
    min_price: 2000000,
    max_price: 12000000,
    min_psf: 1800,
    max_psf: 2400,
    min_sqft: 829,
    max_sqft: 5000,
    bedrooms: JSON.stringify([2, 3, 4, 5]),
    amenities: JSON.stringify(["Olympic Pool", "Tennis Courts", "Gym", "Function Rooms", "BBQ Pits"]),
    description: "Award-winning development by Zaha Hadid in prestigious District 10. Near Holland Village and excellent schools.",
  },
  {
    name: "Reflections at Keppel Bay",
    developer: "Keppel Land",
    address: "1 Keppel Bay View",
    district: 4,
    latitude: 1.2636,
    longitude: 103.8142,
    tenure: "99-year",
    total_units: 1129,
    expected_top: "2011",
    status: "completed",
    min_price: 1600000,
    max_price: 20000000,
    min_psf: 1800,
    max_psf: 2800,
    min_sqft: 700,
    max_sqft: 10000,
    bedrooms: JSON.stringify([1, 2, 3, 4, 5]),
    amenities: JSON.stringify(["Marina", "Infinity Pool", "Gym", "Tennis Court", "Yacht Club Access"]),
    description: "Iconic waterfront development with direct marina access. Designed by Daniel Libeskind.",
  },
  {
    name: "The Interlace",
    developer: "CapitaLand",
    address: "180 Depot Road",
    district: 4,
    latitude: 1.2833,
    longitude: 103.8019,
    tenure: "99-year",
    total_units: 1040,
    expected_top: "2013",
    status: "completed",
    min_price: 1500000,
    max_price: 8000000,
    min_psf: 1400,
    max_psf: 2000,
    min_sqft: 807,
    max_sqft: 4800,
    bedrooms: JSON.stringify([1, 2, 3, 4]),
    amenities: JSON.stringify(["8 Sky Gardens", "Multiple Pools", "Gym", "Tennis Court", "Running Track"]),
    description: "World Building of the Year 2015. Innovative stacked block design with extensive green spaces.",
  },
  {
    name: "Marina One Residences",
    developer: "M+S Pte Ltd",
    address: "23 Marina Way",
    district: 1,
    latitude: 1.2785,
    longitude: 103.8534,
    tenure: "99-year",
    total_units: 1042,
    expected_top: "2017",
    status: "completed",
    min_price: 2200000,
    max_price: 15000000,
    min_psf: 2400,
    max_psf: 3200,
    min_sqft: 538,
    max_sqft: 5000,
    bedrooms: JSON.stringify([1, 2, 3, 4]),
    amenities: JSON.stringify(["Sky Pool", "Gym", "Green Heart", "Retail", "Office Connectivity"]),
    description: "Mixed-use development in Marina Bay. Direct connection to Marina Bay MRT and retail.",
  },
  {
    name: "Parc Riviera",
    developer: "EL Development",
    address: "96 West Coast Vale",
    district: 5,
    latitude: 1.3045,
    longitude: 103.7515,
    tenure: "99-year",
    total_units: 752,
    expected_top: "2019",
    status: "completed",
    min_price: 900000,
    max_price: 2500000,
    min_psf: 1300,
    max_psf: 1600,
    min_sqft: 463,
    max_sqft: 1830,
    bedrooms: JSON.stringify([1, 2, 3, 4]),
    amenities: JSON.stringify(["50m Lap Pool", "Gym", "Tennis Court", "BBQ Pits", "Playground"]),
    description: "Waterfront living along Sungei Ulu Pandan. Near Clementi and West Coast areas.",
  },
  {
    name: "High Park Residences",
    developer: "CEL Development",
    address: "1 Fernvale Close",
    district: 28,
    latitude: 1.3924,
    longitude: 103.8762,
    tenure: "99-year",
    total_units: 1390,
    expected_top: "2019",
    status: "completed",
    min_price: 700000,
    max_price: 1800000,
    min_psf: 1000,
    max_psf: 1300,
    min_sqft: 463,
    max_sqft: 1464,
    bedrooms: JSON.stringify([1, 2, 3, 4, 5]),
    amenities: JSON.stringify(["Multiple Pools", "Gym", "Tennis Court", "Playground", "BBQ Pavilions"]),
    description: "Large-scale development in Sengkang with extensive facilities. Near Thanggam LRT.",
  },
  {
    name: "Treasure at Tampines",
    developer: "Sim Lian Group",
    address: "1 Tampines Lane",
    district: 18,
    latitude: 1.3523,
    longitude: 103.9356,
    tenure: "99-year",
    total_units: 2203,
    expected_top: "2023",
    status: "completed",
    min_price: 1100000,
    max_price: 2800000,
    min_psf: 1300,
    max_psf: 1600,
    min_sqft: 463,
    max_sqft: 2024,
    bedrooms: JSON.stringify([1, 2, 3, 4, 5]),
    amenities: JSON.stringify(["128 Facilities", "Multiple Pools", "Tennis Courts", "Gym", "Function Rooms"]),
    description: "Mega development with 128 facilities. Former HUDC site near Tampines West MRT.",
  },
  {
    name: "JadeScape",
    developer: "Qingjian Realty",
    address: "2 Shunfu Road",
    district: 20,
    latitude: 1.3501,
    longitude: 103.8334,
    tenure: "99-year",
    total_units: 1206,
    expected_top: "2023",
    status: "completed",
    min_price: 1200000,
    max_price: 3500000,
    min_psf: 1600,
    max_psf: 2100,
    min_sqft: 474,
    max_sqft: 2067,
    bedrooms: JSON.stringify([1, 2, 3, 4, 5]),
    amenities: JSON.stringify(["Club House", "Multiple Pools", "Tennis Court", "Gym", "Smart Home"]),
    description: "Near Marymount MRT with smart home features. Walking distance to Junction 8.",
  },
  {
    name: "Stirling Residences",
    developer: "Logan Property & Nanshan Group",
    address: "15 Stirling Road",
    district: 3,
    latitude: 1.2931,
    longitude: 103.8018,
    tenure: "99-year",
    total_units: 1259,
    expected_top: "2022",
    status: "completed",
    min_price: 1100000,
    max_price: 3200000,
    min_psf: 1800,
    max_psf: 2300,
    min_sqft: 441,
    max_sqft: 1776,
    bedrooms: JSON.stringify([1, 2, 3, 4]),
    amenities: JSON.stringify(["Sky Terrace", "Pool", "Gym", "Function Rooms", "BBQ"]),
    description: "Near Queenstown MRT with excellent connectivity. Close to IKEA and Anchorpoint.",
  },
];

async function main() {
  console.log("Seeding resale condos...");

  for (const condo of resaleCondos) {
    // Check if already exists
    const existing = await db.execute({
      sql: "SELECT id FROM condos WHERE name = ?",
      args: [condo.name],
    });

    if (existing.rows.length > 0) {
      console.log(`  ⏭️  ${condo.name} (already exists)`);
      continue;
    }

    await db.execute({
      sql: `
        INSERT INTO condos (
          name, developer, address, district, latitude, longitude,
          tenure, total_units, expected_top, status,
          min_price, max_price, min_psf, max_psf, min_sqft, max_sqft,
          bedrooms, amenities, description
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
      `,
      args: [
        condo.name,
        condo.developer,
        condo.address,
        condo.district,
        condo.latitude,
        condo.longitude,
        condo.tenure,
        condo.total_units,
        condo.expected_top,
        condo.status,
        condo.min_price,
        condo.max_price,
        condo.min_psf,
        condo.max_psf,
        condo.min_sqft,
        condo.max_sqft,
        condo.bedrooms,
        condo.amenities,
        condo.description,
      ],
    });
    console.log(`  ✓ ${condo.name}`);
  }

  console.log("\nSeeded resale condos successfully!");
}

main().catch(console.error);
